### ISSUE TITLE
Missing #include "mkl.h" error when building from source

### ISSUE THREAD

**Issue by stephanegaiffas** [X-DataInitiative/tick#322] opened 2019-01-20 19:28 UTC
/tick/sh/../setup.py:217: DeprecationWarning: SO is deprecated, use EXT_SUFFIX
  sysconfig.get_config_var('SO'))
running build_ext
building 'tick.array.build._array' extension
swigging lib/swig/tick/array/array_module.i to lib/swig/tick/array/array_module_wrap.cpp
swig -python -py3 -c++ -modern -new_repr -Ilib/swig -Ilib/include -outdir tick/array/build -DDEBUG_COSTLY_THROW -o lib/swig/tick/array/array_module_wrap.cpp lib/swig/tick/array/array_module.i
C compiler: gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda3/include -arch x86_64 -I/anaconda3/include -arch x86_64

compile options: '-DSCIPY_MKL_H -DHAVE_CBLAS -DTICK_USE_CBLAS -DTICK_USE_MKL -Iinclude -Iswig -I/anaconda3/include -Ilib/third_party/cereal/include -I/anaconda3/lib/python3.7/site-packages/numpy/core/include -I/anaconda3/include/python3.7m -c'
extra options: '-D_FILE_OFFSET_BITS=64 -DPYTHON_LINK -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -Ilib/include -DTICK_SPARSE_INDICES_INT32 -std=c++11 -O2 -DNDEBUG -ffast-math -Wall -Werror -Wno-uninitialized -DDEBUG_COSTLY_THROW'
gcc: lib/swig/tick/array/array_module_wrap.cpp
gcc: lib/cpp/array/alloc.cpp
In file included from lib/swig/tick/array/array_module_wrap.cpp:3131:
In file included from lib/include/tick/array/carray_python.h:12:
In file included from lib/include/tick/array/array.h:8:
In file included from lib/include/tick/array/basearray.h:6:
In file included from lib/include/tick/array/abstractarray1d2d.h:23:
lib/include/tick/array/vector_operations.h:18:10: fatal error: 'mkl.h' file not found
#include "mkl.h"
         ^~~~~~~
1 error generated.
In file included from lib/swig/tick/array/array_module_wrap.cpp:3131:
In file included from lib/include/tick/array/carray_python.h:12:
In file included from lib/include/tick/array/array.h:8:
In file included from lib/include/tick/array/basearray.h:6:
In file included from lib/include/tick/array/abstractarray1d2d.h:23:
lib/include/tick/array/vector_operations.h:18:10: fatal error: 'mkl.h' file not found
#include "mkl.h"

**Comment by Dekken** [comment] 2019-01-20 19:32
this is a known issue https://github.com/X-DataInitiative/tick/pull/317

it's because conda has MKL, but we don't find the headers

**Comment by Dekken** [comment] 2019-01-20 19:32
you can get around it with


```python3 setup.py build_ext --inplace bdist_wheel```

**Comment by Dekken** [comment] 2019-01-20 20:16
duplicate of

**Closed** 2019-01-29 14:01 UTC
Labels: duplicate
